# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Esencial\Dianita\Proyecto\CompiladoresP1\Views\diagram_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(770, 554)
        Form.setStyleSheet("background-color: rgb(69, 72, 81);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(340, 30, 131, 21))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 80, 651, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_diagram = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_diagram.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_diagram.setObjectName("verticalLayout_diagram")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "DIAGRAMA UML"))
