# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Esencial\Dianita\Proyecto\CompiladoresP1\Views\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1144, 646)
        MainWindow.setStyleSheet("background-color: rgb(39, 39, 39);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_Campo = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Campo.setGeometry(QtCore.QRect(30, 220, 501, 351))
        self.textEdit_Campo.setStyleSheet("border: 2px solid;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"border-color: rgb(255, 255, 0);")
        self.textEdit_Campo.setObjectName("textEdit_Campo")
        self.pushButton_analizarCodigo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_analizarCodigo.setGeometry(QtCore.QRect(370, 590, 161, 41))
        self.pushButton_analizarCodigo.setStyleSheet("background-color: rgb(242, 219, 25);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;\n"
"font: 63 8pt \"Segoe UI Semibold\";")
        self.pushButton_analizarCodigo.setObjectName("pushButton_analizarCodigo")
        self.pushButton_buscarArchivo = QtWidgets.QToolButton(self.centralwidget)
        self.pushButton_buscarArchivo.setGeometry(QtCore.QRect(510, 90, 31, 21))
        self.pushButton_buscarArchivo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_buscarArchivo.setObjectName("pushButton_buscarArchivo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 90, 121, 20))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 8pt \"Segoe UI Semibold\";")
        self.label.setObjectName("label")
        self.pushButton_cargarArchivo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cargarArchivo.setGeometry(QtCore.QRect(270, 120, 111, 31))
        self.pushButton_cargarArchivo.setStyleSheet("background-color: rgb(255, 54, 3);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"font: 63 8pt \"Segoe UI Semibold\";")
        self.pushButton_cargarArchivo.setObjectName("pushButton_cargarArchivo")
        self.textField_selected_file = QtWidgets.QLineEdit(self.centralwidget)
        self.textField_selected_file.setGeometry(QtCore.QRect(150, 80, 351, 31))
        self.textField_selected_file.setAccessibleDescription("")
        self.textField_selected_file.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.textField_selected_file.setInputMask("")
        self.textField_selected_file.setText("")
        self.textField_selected_file.setPlaceholderText("")
        self.textField_selected_file.setObjectName("textField_selected_file")
        self.label_alert = QtWidgets.QLabel(self.centralwidget)
        self.label_alert.setGeometry(QtCore.QRect(280, 160, 81, 16))
        self.label_alert.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_alert.setObjectName("label_alert")
        self.label_file_sucessful = QtWidgets.QLabel(self.centralwidget)
        self.label_file_sucessful.setGeometry(QtCore.QRect(270, 160, 101, 20))
        self.label_file_sucessful.setStyleSheet("color: rgb(0, 170, 0);")
        self.label_file_sucessful.setAlignment(QtCore.Qt.AlignCenter)
        self.label_file_sucessful.setObjectName("label_file_sucessful")
        self.pushButton_limpiarCodigo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_limpiarCodigo.setGeometry(QtCore.QRect(60, 600, 161, 41))
        self.pushButton_limpiarCodigo.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(242, 219, 25);\n"
"border-radius: 15px;\n"
"font: 63 8pt \"Segoe UI Semibold\";")
        self.pushButton_limpiarCodigo.setObjectName("pushButton_limpiarCodigo")
        self.tabla_tokens = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_tokens.setGeometry(QtCore.QRect(600, 80, 321, 491))
        self.tabla_tokens.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.tabla_tokens.setObjectName("tabla_tokens")
        self.tabla_tokens.setColumnCount(3)
        self.tabla_tokens.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_tokens.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_tokens.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_tokens.setHorizontalHeaderItem(2, item)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(470, 10, 231, 41))
        self.label_2.setStyleSheet("font: 81 20pt \"Rockwell Extra Bold\";\n"
"color: rgb(247, 224, 24);")
        self.label_2.setObjectName("label_2")
        self.pushButton_erroresLexico = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_erroresLexico.setGeometry(QtCore.QRect(670, 590, 201, 41))
        self.pushButton_erroresLexico.setStyleSheet("background-color: rgb(222, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"font: 63 8pt \"Segoe UI Semibold\";")
        self.pushButton_erroresLexico.setObjectName("pushButton_erroresLexico")
        self.label_lexicoValido = QtWidgets.QLabel(self.centralwidget)
        self.label_lexicoValido.setGeometry(QtCore.QRect(930, 240, 201, 21))
        self.label_lexicoValido.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 63 12pt \"Segoe UI Semibold\";")
        self.label_lexicoValido.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lexicoValido.setObjectName("label_lexicoValido")
        self.label_sintaticoValido = QtWidgets.QLabel(self.centralwidget)
        self.label_sintaticoValido.setGeometry(QtCore.QRect(940, 290, 201, 21))
        self.label_sintaticoValido.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 63 12pt \"Segoe UI Semibold\";")
        self.label_sintaticoValido.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sintaticoValido.setObjectName("label_sintaticoValido")
        self.label_tablaSintaxis = QtWidgets.QLabel(self.centralwidget)
        self.label_tablaSintaxis.setGeometry(QtCore.QRect(770, 40, 201, 21))
        self.label_tablaSintaxis.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 12pt \"Segoe UI Semibold\";")
        self.label_tablaSintaxis.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tablaSintaxis.setObjectName("label_tablaSintaxis")
        self.label_lexicoInvalido = QtWidgets.QLabel(self.centralwidget)
        self.label_lexicoInvalido.setGeometry(QtCore.QRect(940, 240, 201, 21))
        self.label_lexicoInvalido.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 63 12pt \"Segoe UI Semibold\";")
        self.label_lexicoInvalido.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lexicoInvalido.setObjectName("label_lexicoInvalido")
        self.label_sintaticoInvalido = QtWidgets.QLabel(self.centralwidget)
        self.label_sintaticoInvalido.setGeometry(QtCore.QRect(940, 290, 211, 21))
        self.label_sintaticoInvalido.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 63 12pt \"Segoe UI Semibold\";")
        self.label_sintaticoInvalido.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sintaticoInvalido.setObjectName("label_sintaticoInvalido")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_analizarCodigo.setText(_translate("MainWindow", "ANALIZAR CÓDIGO"))
        self.pushButton_buscarArchivo.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Selecccionar archivo:"))
        self.pushButton_cargarArchivo.setText(_translate("MainWindow", "Cargar archivo"))
        self.label_alert.setText(_translate("MainWindow", "Import a file!"))
        self.label_file_sucessful.setText(_translate("MainWindow", "File Sucessful!"))
        self.pushButton_limpiarCodigo.setText(_translate("MainWindow", "LIMPIAR CÓDIGO"))
        item = self.tabla_tokens.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "TOKENS"))
        item = self.tabla_tokens.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "VALORES"))
        item = self.tabla_tokens.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "POSICION"))
        self.label_2.setText(_translate("MainWindow", "JAVASCRIPT"))
        self.pushButton_erroresLexico.setText(_translate("MainWindow", "VER ERRORES DE LÉXICO"))
        self.label_lexicoValido.setText(_translate("MainWindow", "LÉXICO VÁLIDO"))
        self.label_sintaticoValido.setText(_translate("MainWindow", "SINTACTICO VÁLIDO"))
        self.label_tablaSintaxis.setText(_translate("MainWindow", "TABLA DE SINTAXIS"))
        self.label_lexicoInvalido.setText(_translate("MainWindow", "LÉXICO INVÁLIDO"))
        self.label_sintaticoInvalido.setText(_translate("MainWindow", "SINTACTICO INVÁLIDO"))
